{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 48,
   "metadata": {},
   "outputs": [],
   "source": [
    "import altair as alt\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "\n",
    "# Compute x^2 + y^2 across a 2D grid\n",
    "x, y = np.meshgrid(range(-5, 5), range(-5, 5))\n",
    "z = x ** 2 + y ** 2\n",
    "\n",
    "# Convert this grid to columnar data expected by Altair\n",
    "source = pd.DataFrame({'x': x.ravel(),\n",
    "                     'y': y.ravel(),\n",
    "                     'z': z.ravel()})\n",
    "\n",
    "chart = alt.Chart(source).mark_rect().encode(\n",
    "    x='x:O',\n",
    "    y='y:O',\n",
    "    color='z:Q'\n",
    ")\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 49,
   "metadata": {},
   "outputs": [],
   "source": [
    "viz_message = {\n",
    "    \"id\": \"id002\",\n",
    "    \"type\": \"vega-lite\",\n",
    "    \"data\": str(chart.to_json()),\n",
    "    \"title\": \"Example Heatmap\",\n",
    "    \"description\": \"A simple heatmap example in vega-lite using Altair\",\n",
    "    \"category\": \"topic_modelling\",\n",
    "    \"narrative\": \"test_narrative\",\n",
    "    \"feedId\": \"id0\",\n",
    "    \"sourceId\": \"id1\",\n",
    "    \"articleId\": \"id2\"\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 51,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread 69: pykafka.OwnedBroker.queue_reader for broker 1:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\kuilthvd\\Documents\\Python\\Python39\\lib\\site-packages\\pykafka\\producer.py\", line 619, in queue_reader\n",
      "    batch = self.flush(self.producer._linger_ms, self.producer._max_request_size)\n",
      "ReferenceError: weakly-referenced object no longer exists\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\kuilthvd\\Documents\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\kuilthvd\\Documents\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\kuilthvd\\Documents\\Python\\Python39\\lib\\site-packages\\pykafka\\producer.py\", line 624, in queue_reader\n",
      "    self.producer._worker_exception = sys.exc_info()\n",
      "ReferenceError: weakly-referenced object no longer exists\n",
      "Exception in thread 41: pykafka.OwnedBroker.queue_reader for broker 1:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\kuilthvd\\Documents\\Python\\Python39\\lib\\site-packages\\pykafka\\producer.py\", line 619, in queue_reader\n",
      "    batch = self.flush(self.producer._linger_ms, self.producer._max_request_size)\n",
      "ReferenceError: weakly-referenced object no longer exists\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\kuilthvd\\Documents\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\kuilthvd\\Documents\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\kuilthvd\\Documents\\Python\\Python39\\lib\\site-packages\\pykafka\\producer.py\", line 624, in queue_reader\n",
      "    self.producer._worker_exception = sys.exc_info()\n",
      "ReferenceError: weakly-referenced object no longer exists\n",
      "Exception in thread 27: pykafka.OwnedBroker.queue_reader for broker 1:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\kuilthvd\\Documents\\Python\\Python39\\lib\\site-packages\\pykafka\\producer.py\", line 619, in queue_reader\n",
      "    batch = self.flush(self.producer._linger_ms, self.producer._max_request_size)\n",
      "ReferenceError: weakly-referenced object no longer exists\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\kuilthvd\\Documents\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\kuilthvd\\Documents\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\kuilthvd\\Documents\\Python\\Python39\\lib\\site-packages\\pykafka\\producer.py\", line 624, in queue_reader\n",
      "    self.producer._worker_exception = sys.exc_info()\n",
      "ReferenceError: weakly-referenced object no longer exists\n",
      "Exception in thread 83: pykafka.OwnedBroker.queue_reader for broker 1:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\kuilthvd\\Documents\\Python\\Python39\\lib\\site-packages\\pykafka\\producer.py\", line 619, in queue_reader\n",
      "    batch = self.flush(self.producer._linger_ms, self.producer._max_request_size)\n",
      "ReferenceError: weakly-referenced object no longer exists\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\kuilthvd\\Documents\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\kuilthvd\\Documents\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\kuilthvd\\Documents\\Python\\Python39\\lib\\site-packages\\pykafka\\producer.py\", line 624, in queue_reader\n",
      "    self.producer._worker_exception = sys.exc_info()\n",
      "ReferenceError: weakly-referenced object no longer exists\n",
      "Exception in thread 55: pykafka.OwnedBroker.queue_reader for broker 1:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\kuilthvd\\Documents\\Python\\Python39\\lib\\site-packages\\pykafka\\producer.py\", line 619, in queue_reader\n",
      "    batch = self.flush(self.producer._linger_ms, self.producer._max_request_size)\n",
      "ReferenceError: weakly-referenced object no longer exists\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\kuilthvd\\Documents\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\kuilthvd\\Documents\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\kuilthvd\\Documents\\Python\\Python39\\lib\\site-packages\\pykafka\\producer.py\", line 624, in queue_reader\n",
      "    self.producer._worker_exception = sys.exc_info()\n",
      "ReferenceError: weakly-referenced object no longer exists\n",
      "WARNING:root:kafka consumer for topic b'simulation_time_mgmt'was stopped\n"
     ]
    }
   ],
   "source": [
    "from test_bed_adapter.options.test_bed_options import TestBedOptions\n",
    "from test_bed_adapter import TestBedAdapter\n",
    "\n",
    "#Use these if running outside of a docker image\n",
    "#KAFKA_HOST = '127.0.0.1:3501'\n",
    "#SCHEMA_REGISTRY = 'http://localhost:3502'\n",
    "\n",
    "KAFKA_HOST = 'broker:9092'\n",
    "SCHEMA_REGISTRY = 'http://schema_registry:8081'\n",
    "CLIENT_ID = 'JUPYTER_NOTEBOOK'\n",
    "CONSUME = []\n",
    "PRODUCE = [\"visualization_item_generic\"]\n",
    "\n",
    "options = {\n",
    "            \"kafka_host\": KAFKA_HOST,\n",
    "            \"schema_registry\": SCHEMA_REGISTRY,\n",
    "            \"fetch_all_versions\": False,\n",
    "            \"from_off_set\": True,\n",
    "            \"client_id\": CLIENT_ID,\n",
    "            \"consume\": CONSUME,\n",
    "            \"produce\": PRODUCE\n",
    "        }\n",
    "\n",
    "test_bed_adapter = TestBedAdapter(TestBedOptions(options))\n",
    "\n",
    "test_bed_adapter.initialize()\n",
    "\n",
    "message = {\"message\": viz_message}\n",
    "messages = 1 * [message]\n",
    "test_bed_adapter.producer_managers[PRODUCE[0]].send_messages(messages)\n",
    "\n",
    "\n",
    "test_bed_adapter.stop()"
   ]
  }
 ],
 "metadata": {
  "interpreter": {
   "hash": "079e56c5ebeda1d41e9fd14b00156f9d69d5f8697ef1eb8bf62e272d5cc04519"
  },
  "kernelspec": {
   "display_name": "Python 3.9.7 64-bit",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
